"""Manual smoke test of the REAL Gmail integration (step 10). NOT part of the pytest suite.

Sends ONE real, synthetic test e-mail through the real Gmail API, to an address YOU provide
explicitly on the command line (never hardcoded, never guessed, never a candidate contact).

    python scripts/manual/gmail_smoke_test.py --to your-own-address@example.com

Requires: SEND_MODE=auto and MAIL_FROM set in .env (or --from), a configured database (every
send is audited), and the three Gmail secrets already stored:
    python scripts/manage_secrets.py set gmail_client_id
    python scripts/manage_secrets.py set gmail_client_secret
    python scripts/manual/gmail_oauth_setup.py   (stores gmail_refresh_token)

This goes through the EXACT same `SendGuard` -> audit -> `MailSender` -> `GmailClient` path as a
real batch send (`approved=True`, the same way `app.services.send_batch` would pass it after its
own preflight checks) - nothing here is a separate, untested code path. No CV attachment unless
you pass --attach; the subject/body are synthetic, never real candidate content.

Never prints a token, a secret, or message content beyond what you typed on the command line.
"""

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]

from app.core.config import ConfigurationError, SendMode, get_settings  # noqa: E402
from app.core.database import get_session_factory  # noqa: E402
from app.core.errors import DomainError  # noqa: E402
from app.core.secrets import SecretStoreError, get_secret_store  # noqa: E402
from app.integrations.gmail.client import GmailClient  # noqa: E402
from app.integrations.mail.ports import AttachmentRef, OutgoingEmail  # noqa: E402
from app.services.audit import AuditLog  # noqa: E402
from app.services.mail_sender import MailSender  # noqa: E402

DEFAULT_SUBJECT = "Career Agent Gmail smoke test"
DEFAULT_BODY = "Synthetic test message generated by career-agent's manual Gmail smoke test."


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--to", required=True, help="a real address YOU control")
    parser.add_argument("--from", dest="sender", default=None)
    parser.add_argument("--subject", default=DEFAULT_SUBJECT)
    parser.add_argument(
        "--attach", action="append", default=[], help="path relative to data/private/"
    )
    args = parser.parse_args(argv)

    settings = get_settings()
    try:
        if settings.send_mode is not SendMode.AUTO:
            raise ConfigurationError("SEND_MODE must be 'auto' for this smoke test.")
        sender = args.sender or settings.mail_from
        if not sender:
            raise ConfigurationError("MAIL_FROM is not set (or pass --from).")
        settings.require_database_url()

        store = get_secret_store()
        email = OutgoingEmail(
            sender=sender,
            to=args.to,
            subject=args.subject,
            body_text=DEFAULT_BODY,
            attachments=tuple(AttachmentRef(path) for path in args.attach),
        )
        with get_session_factory()() as session:
            result = MailSender(
                settings,
                AuditLog(session),
                live_provider=GmailClient(store),
                actor="cli",
            ).send(email, approved=True)
    except (DomainError, ConfigurationError, OSError, SecretStoreError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1

    print(f"Decision: {result.decision.action.value} ({result.decision.reason})")
    if result.sent is None:
        print("Nothing was sent.")
        return 1
    print(f"Sent via {result.sent.provider}: message id {result.sent.provider_message_id}")
    if result.sent.thread_id:
        print(f"Thread id: {result.sent.thread_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
