"""Build a message (with attachments) and write it as a local .eml. Nothing is ever sent.

    python scripts/dry_run_mail.py --to someone@example.invalid --attach documents/<cv>.docx

Requires SEND_MODE=dry_run, MAIL_FROM (or --from) and a configured database (every send
attempt, even a dry run, is audited). The .eml is written to data/private/outbox/ only. The
terminal shows counters and the outbox location, never the message content.
"""

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from app.core.config import ConfigurationError, get_settings
from app.core.database import get_session_factory
from app.core.errors import DomainError
from app.integrations.mail.ports import AttachmentRef, OutgoingEmail
from app.services.audit import AuditLog
from app.services.mail_sender import MailSender

DEFAULT_SUBJECT = "Career Agent dry-run test"
DEFAULT_BODY = "Synthetic test message generated by career-agent (dry run, never sent)."


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--to", required=True)
    parser.add_argument("--from", dest="sender", default=None)
    parser.add_argument("--subject", default=DEFAULT_SUBJECT)
    parser.add_argument("--body-file", type=Path, default=None)
    parser.add_argument(
        "--attach", action="append", default=[], help="path relative to data/private/"
    )
    args = parser.parse_args(argv)

    settings = get_settings()
    try:
        sender = args.sender or settings.mail_from
        if not sender:
            raise ConfigurationError("MAIL_FROM is not set (or pass --from).")
        settings.require_database_url()  # sending, even a dry run, is always audited
        body = args.body_file.read_text(encoding="utf-8") if args.body_file else DEFAULT_BODY
        email = OutgoingEmail(
            sender=sender,
            to=args.to,
            subject=args.subject,
            body_text=body,
            attachments=tuple(AttachmentRef(path) for path in args.attach),
        )
        with get_session_factory()() as session:
            result = MailSender(settings, AuditLog(session), actor="cli").send(email)
    except (DomainError, ConfigurationError, OSError) as error:
        print(f"Error: {error}", file=sys.stderr)  # generic messages, never message content
        return 1

    print(f"Decision: {result.decision.action.value} ({result.decision.reason})")
    if result.sent is None:
        print("Nothing was written or sent.")
        return 1
    print(f"Written: {result.sent.location} (inside the private data directory)")
    print("Nothing was sent: no network call was made.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
